#!/usr/bin/env bash

# run from repo root dir

if [[ -f ".env" || -f ".ngrok.yml" ]]; then
  echo ".env and/or .ngrok.yml already exists"
  exit 1
fi

SUBDOMAIN="$( \
  openssl rand -base64 20 | \
  tr -d "=+/" | \
  cut -c1-16 \
  )"
SECRET="$(openssl rand -base64 32)"
APP_NAME="Pro Auth Bot (${SUBDOMAIN})"

tee .ngrok.yml << EOF
tunnels:
  probot:
    proto: http
    addr: localhost:3000
    bind_tls: true
    subdomain: ${SUBDOMAIN}
EOF

tee .env << EOF
WEBHOOK_SECRET=${SECRET}
EOF

cp app.template.yml app.yml
tee -a app.yml << EOF

name: ${APP_NAME}
EOF
